### ISSUE TITLE
concept uitschrijven en git klaarzetten

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#1]
Beste,
In de ReadMe file heb ik mijn concept uitgeschreven. Ik vroeg mij af of dit goedgekeurd is. 
Ik heb ook nog een vraag omtrent de extra service die wij moeten gebruiken. Ik heb enkele voorgestelde services uit de lessen bekeken en vind dat deze eigenlijk allemaal een beetje hetzelfde doen als Strapi. Moeten wij deze dan alle twee gebruiken of niet? Ik denk dat ik Getform wil gebruiken als dat oké is.  (https://app.getform.io/)

Alvast bedankt!

**Comment by benoitboucart** [comment]
Je concept moest je inderdaad via een issue voorleggen om er feedback op te krijgen.

Bij deze: je concept is oké maar is nog te beperkt beschreven.
Hoe kan de gebruiker een taart samenstellen? Kiest hij de ingrediënten? Hoe wordt die gevisualiseerd? Hoe kan zij/hij haar/zijn wensen meegeven? Wat ziet de gebruiker die de wensen krijgt? Hoe krijgt de persoon de wensen?

Heb je ook gedacht aan de integraties / (nieuwe) technologieën die je zal implementeren?

Hoe ga je GetForm gebruiken en waarom? 
Je mag Strapi gebruiken hoor. Zorg gewoon dat je ook andere diensten integreert / je experimenteert met nieuwe technologieën / tools zoals in de opdrachtfiche is beschreven.

**Comment by Tara-Tessa** [comment]
Ik heb mijn concept wat aangepast en twee services gevonden waar ik misschien mee wil werken. Zouden deze goed zijn?

**Comment by SimonVanherweghe** [comment]
Momentjs en die Spinner zijn geen services maar libraries, npm-packages. Die getform is wél een service, dus dat is op zich al ok.

Let er ook op dat er ondertussen [betere oplossingen zijn dan momentjs](https://momentjs.com/docs/#/-project-status/)
