### ISSUE TITLE
ChangeClasses in aparte component

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#14]
Ik wilde mijn code optimaliseren door twee keer dezelfde functies te vervangen door 1x deze functie in een aparte component. Nu ben ik op het probleem gebotst dat bij de ene aanroep van mijn functie ik 1 value terug krijg in de stateValue die ik dan deco noem en daarmee al mijn if-statements maak, en bij de andere aanroep ik een array terug krijg waarvan ieder item via een map een deco zou moeten worden.

Hier zie misschien beter wat ik bedoel en ook hoe ik dit probeer op te lossen:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/a707236b3ca5fc0e661fe9eb20a7d4e194c7aca1/components/ChangeClass.js#L10-L18

Nu toont hij steeds alleen het laatste item in de array.

Alvast hartelijk bedankt!

**Comment by SimonVanherweghe** [comment]
Euh, dit is vreemd:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/a707236b3ca5fc0e661fe9eb20a7d4e194c7aca1/components/ChangeClass.js#L13-L15

Met een map overloop je elk element in een array en krijg je een nieuwe array terug maar met elk element aangepast door de callback functie. Jij gebruikt die map als een foreach, gewoon overlopen, niks returnen.

Omdat je hier een foreach gebruikt, overloopt hij alle items in die array, en gaat hij met elk item _telkens_ de state updaten. Op het einde is de state gelijk aan het laatste element in de array.

Ik zie dat je eens uw 'deco' gebruikt als string en de andere keer als array.
Ik zou dit altijd als een array doen, telkens checken met .includes, werkt voor 1 of meerdere items in de deco.
