### ISSUE TITLE
Redirect na submit van form

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#15]
Als ik probeer om bij het versturen van mijn form en redirect te doen naar de net aangemaakte pagina dan doet hij na 2sec gewoon een refresh van mijn home (pagina waar de form staat).

Ik doe het nu op deze manier:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/a707236b3ca5fc0e661fe9eb20a7d4e194c7aca1/components/AddCake.js#L121

Maar heb ook al zo geprobeerd:
router.push(/cakes/:${data.nanoid})

Mijn router is zo aangemaakt:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/a707236b3ca5fc0e661fe9eb20a7d4e194c7aca1/components/AddCake.js#L23

Alvast hartelijk bedankt!

**Comment by SimonVanherweghe** [comment]
Dit zal op zich niet werken, als je de nanoid() functie aanroept, krijg je telkens een ander id terug.
Je roept deze best één keer aan, stopt het resultaat in een variabele, en doet dan met die variabele verder.

Je wacht best (via een await) tot je onSubmit klaar is (ik zie dat die functie toch al async is) om pas daarna die redirect te doen.

**Comment by Tara-Tessa** [comment]
Beste,

Het lukt nu om te redirecten naar een succespagina, maar ik krijg steeds deze foutmelding:
![image](https://user-images.githubusercontent.com/72027571/116779176-f0ee2800-aa74-11eb-82f2-2a6a7a2f3aaa.png)

Hier doe ik de redirect naar de succespagina en geef ik de gegevens mee zodat deze sowieso al getoond kunnen worden:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/813171d02feae0b62880183f2f09314e905961d3/components/AddCake.js#L124-L127

Hier roep ik deze gegevens dan weer op in mijn succespagina om dan verder door te sturen naar de component ChangeClass waar ik mijn taart opbouw:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/813171d02feae0b62880183f2f09314e905961d3/pages/cakes/success.js#L15-L16

Het is daar dat ik die error krijg (replace of undefined...) uit de png. 
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/813171d02feae0b62880183f2f09314e905961d3/components/ChangeClass.js#L79-L81

Dit komt denk ik omdat deze waarden (stateFondant, stateCake, stateTiers,...) eerst nog niet zijn ingevuld en dus moeten wachten tot de pagina helemaal ingeladen is en dus eerst undefined zijn. 

Als ik veel dingen aanpas in mijn ChangeClass dan heeft dit ook gevolgen voor andere pagina's aangezien ik deze code hergebruik op de addCake pagina en de detailpagina.

Ik weet dus niet hoe ik dit het beste aanpak.

Alvast hartelijk bedankt!

**Comment by benoitboucart** [comment]
Je moet dan wachten tot de state beschikbaar is als volgt (net als wat we bij useFetch hebben gedaan in Create React App waarbij men moest wachten op het vervolledigen van de fetch request):

```
 {stateFondant && stateTiers && stateCake && 
    <div className={styles[stateFondant.replace(/\s+/g, '').toLowerCase()]}></div> 
    <div className={styles[stateTiers.replace(/\s+/g, '').toLowerCase()]}></div> 
    <div className={styles[stateCake.replace(/\s+/g, '').toLowerCase()]}></div> 
 }
```

Of indien je alles in 1 state object zou steken (properder):
```
 {cakeInfo && 
    <div className={styles[cakeInfo.fondant.replace(/\s+/g, '').toLowerCase()]}></div> 
    <div className={styles[cakeInfo.tiers.replace(/\s+/g, '').toLowerCase()]}></div> 
    <div className={styles[cakeInfo.cake.replace(/\s+/g, '').toLowerCase()]}></div> 
 }
```

**Comment by Tara-Tessa** [comment]
Ik krijg nu deze foutmelding te zien:
![image](https://user-images.githubusercontent.com/72027571/116781870-10418100-aa86-11eb-915e-5ae7a9a096fd.png)

Alvast bedankt!

**Comment by benoitboucart** [comment]
De "if" moet je binnen de hook zetten. 

![image](https://user-images.githubusercontent.com/1086264/116782492-b478f700-aa89-11eb-80eb-6f830c1af82e.png)

Zie ook hooks rules: https://reactjs.org/docs/hooks-rules.html
