### ISSUE TITLE
Client en Server klaarzetten en gegevens ophalen.

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#2]
Als ik probeer om data uit strapi te halen in de Tiers component dan krijg ik steeds een __proto__: Object binnen. In de index kan ik wel gewoon data ophalen.
Alvast bedankt
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/64dffaf372b1a21348cdc97275d61077dce32763/components/Tiers.js#L2

**Comment by benoitboucart** [comment]
Je moet een key meegeven, bijvoorbeeld:
![image](https://user-images.githubusercontent.com/1086264/114558093-9f6b2e00-9c6a-11eb-9f3c-5d4d21c744eb.png)

Als dit niet werkt kan je verder debuggen als volgt:
![image](https://user-images.githubusercontent.com/1086264/114558309-d3465380-9c6a-11eb-871a-51c1de54e4b0.png)


Voeg je in het vervolg een screenshot toe van wat je in je console terugkrijgt? Of nog beter een copy/paste? Is dan gemakkelijker voor ons om te helpen.

**Comment by Tara-Tessa** [comment]
Dit is wat ik te zien krijg in de console als ik het log in de component boven de getStaticProps functie:

{}
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()

Als ik de data console.log in de getStaticProps zelf krijg ik niets terug in de terminal.
Zou dit misschien kunnen liggen aan dat ik dit in een component in de components map doe en niet in de pages?
Alvast bedankt

**Comment by benoitboucart** [comment]
Yep, inderdaad, had ik niet gezien. 
Dit kan je enkel oproepen op "Page" niveau, dus inderdaad in de Pages. Je kan die data uiteraard doorgeven via props aan specifieke componenten.

**Comment by Tara-Tessa** [comment]
Ik heb de tiers.js pagina nu verplaatst naar binnen de pages, maar dit werkt nog steeds niet. Als ik dit in de index doe lukt het wel, maar daar doe ik al een fetch naar totals en ik snap niet goed hoe je dan twee fetches op dezelfde pagina kan doen. Ik krijg nog steeds dit in de console en in de terminal niets:
{}
proto:
constructor: ƒ Object().
Alvast bedankt

**Comment by benoitboucart** [comment]
Als de homepagina werkt kan je eens je index.js duppliceren en hernoem het naar iets anders. Verander het component naam van deze pagina (dus `Home`) en surf dan naar deze nieuwe pagina.

Verschillende fetches kan als volgt, je beslist zelf wat je doorgeeft aan de props van de pagina (zie ook screenshot in eerdere comment met info over werking):

![image](https://user-images.githubusercontent.com/1086264/114677529-afd2e580-9d0a-11eb-8e43-f0bedde05c39.png)
