### ISSUE TITLE
Vervang Strapi door Contentful

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#7]
Als ik probeer om de data door te sturen naar contentful krijg ik steeds deze error terug:
contentful.createEntry is not a function
in de console krijg ik:
Uncaught (in promise) TypeError: Object(...) is not a function

Ik weet niet hoe ik dit kan oplossen. Ik heb al verschillende methodes gebruikt om de data door te sturen en nu probeer ik deze:
https://contentful.github.io/contentful-management.js/contentful-management/5.0.0-beta2/ContentfulSpaceAPI.html#.createEntry

Alvast hartelijk bedankt!

https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/b8cc2822cf5b3d724fcec0b30bf91f2823fd7f3f/pages/index.js#L15-L40

**Comment by benoitboucart** [comment]
Dag Tara-Tessa,

Dit mag je niet op deze manier requiren (zou sowieso altijd bovenaan moeten staan):
![image](https://user-images.githubusercontent.com/1086264/115550609-56d6f480-a2aa-11eb-8f8e-a36acb8b69d6.png)

Wel als volgt (zie ook tutorial hieronder): 
![image](https://user-images.githubusercontent.com/1086264/115550808-9271be80-a2aa-11eb-80e4-bdf7777b2df3.png)

Heb je ook `NEXT_PUBLIC_CONTENTFUL_ACCES_KEY` al gelogd om te checken of de key correct is?

Hier vind je ook een volledige reeks hierover:
https://www.youtube.com/watch?v=m9mNsYJbkNg

En hier de integratie in Next: https://www.youtube.com/watch?v=sougdtlQlEk

Succes.

**Comment by Tara-Tessa** [comment]
Als ik probeer om dit zo te importeren krijg ik foutmelding dat dit niet bestaat:
import { contentful } from 'contentful-management'
Als ik probeer om dit te importeren krijg ik een foutmelding in mijn getStaticProps omdat dit dan dezelfde naam heeft:
import { createClient } from 'contentful-management'

Als ik NEXT_PUBLIC_CONTENTFUL_ACCES_KEY log dan toont deze de juiste key.

Ik heb die filmpjes inderdaad al bekeken en deze zijn heel handig, maar ze tonen alleen maar een get request en geen push.
Als ik hier over opzoek vind ik ook niet veel resultaten.

Alvast bedankt!

**Comment by benoitboucart** [comment]
Waarom `from 'contentful-management'` en niet `from 'contentful'` zoals in de tutorial?
Heb je contentful toegevoegd aan je project?

En graag ook foutmelding delen als je een foutmelding krijgt. "foutmelding dat dit niet bestaat" is te vaag omschreven.

**Comment by Tara-Tessa** [comment]
In deze tutorial wordt getoond dat je een createClient moet uitvoeren om contentful. Deze contentful halen ze in de tutorial op via: const contentful = require('contentful-management'). 

Als ik probeer om deze te importen in plaats van met die require te werken via import { contentful } from 'contentful-management' krijg ik deze foutmelding:
Attempted import error: 'contentful' is not exported from 'contentful-management'.

Als ik het dan doe met import { createClient } from 'contentful-management' krijg ik:
Syntax error: Identifier 'createClient' has already been declared
Deze is al gedeclareerd om de fetch te doen (client.getEntries({content_type: 'total'})) van uit contentful (import { createClient } from 'contentful'), maar deze bevat niet de functie .createEntry en die uit content-management zou deze dan wel bevatten denk ik.

tutorial: https://contentful.github.io/contentful-management.js/contentful-management/5.0.0-beta2/ContentfulSpaceAPI.html#.createEntry

Alvast bedankt!

**Comment by SimonVanherweghe** [comment]
Even wat verduidelijken:

Er zijn 2 versies van de API: de content delivery en de content management
De eerste is vooral om uit te lezen, de 2de is om de structuur te beheren én om te schrijven.
https://www.contentful.com/developers/docs/references/

Als je iets wil aanmaken, heb je dus de content managament api (en bijhorende token) nodig
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry/create-update-an-entry/console/js

Je hebt dan ook de bijhorende client library nodig. `contentful` is niet hetzelfde als `contentful-management`

Als je de beide nodig hebt in één file, kan je het als volgt doen, want anders zal het idd in de soep lopen.
```
import { createClient as deliveryClient } from "contentful";
import { createClient as managementClient } from "contentful-management";
```
Je gebruikt dan verder `deliveryClient` en `managementClient` in jouw code


Wel oppassen: jouw tokens/keys staan publiek (ze zijn geprefixed met `next_public`) Dit is niet ok, iedereen kan zo aan je tokens en -aangezien het van de content-managment api is- zelfs jouw structuur aanpassen.
Hiervoor bieden de API routes van Next de perfecte oplossing. Maak daar een POST route aan waarin je die contentful api aanspreekt. Vanuit jouw eventHandler kan je dan die API route gebruiken. Dit is eigenlijk dezelfde werkwijze als de buttondown integratie vanuit de Video Topics. Zeker eens bekijken (mocht je dat nog niet gedaan hebben)

PS: Je kan al jouw 'queries' van en naar contentful samen in één file zetten in aparte functies (onder /services/data.js of zo, naam maakt niet uit) en dan kan van overal (vanuit getStaticProps of vanuit de API routes) die functies aanspreken. Proper gestructureerd, tokens zitten niet overal verspreid in je code en je kan deze dan makkelijk her-gebruiken

**Comment by Tara-Tessa** [comment]
Beste,

Ik ben bezig met die API routes in te stellen, maar krijg steeds de foutmelding:
PUT [http://localhost:3000/api/post](http://localhost:3000/api/post) 500 (Internal Server Error)
Uncaught (in promise) SyntaxError: Unexpected token S in JSON at position 0

Als ik dan klik op die Uncaught... error dan krijg ik dit te zien:
Something went wrong: TypeError: Only absolute URLs are supported

Ik heb al in verschillende punten console log gedaan en denk dat mijn fetch naar de api key niet correct wordt uitgevoerd of dat deze dus niet klopt. 
Ik doe dit volgens het filmpje uit de Topics en via dit "artikel" die u mij doorstuurde:
https://www.contentful.com/developers/docs/references/content-management-api/#/reference/entries/entry/create-update-an-entry/console/js

Alvast bedankt!

Permalink: https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/fed70c4e7624fec8298f6f6447974d59cfe4afec/pages/api/post.js#L5

**Comment by SimonVanherweghe** [comment]
Je hoeft dat niet via de REST API van contentful te doen hoor, je kan daar gerust de js client libaray van contentful gebruiken.

De foutmelding die je krijgt is dat je iets wil fetchen dat start met een '/' (/spaces...) Dat zou een volledige url moeten zijn (http://....) Maar als je daar de JS Client Library gebruikt, is dat niet van toepassing.

**Comment by Tara-Tessa** [comment]
Ik snap niet goed wat je bedoeld met de JS Client Library van Contentful is dat dan zoals hier:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/dc0b15fe9210ec771ef0cc71b55f6174de830bf2/pages/api/post.js#L10

Ik krijg hierbij nog steeds dezelfde foutmeldingen (Only absolute URLs are supported).
Alvast hartelijk bedankt!

**Comment by Tara-Tessa** [comment]
Ik heb het nu zo geprobeerd ook. Ik weet niet of dit beter is of niet:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/3d87748d8afc3827541a22711ed6e37ffe262c7a/pages/api/post.js#L6

hierbij krijg ik de foutmelding:
"An access token is required. Please send one through the HTTP Authorization header or as the query parameter "access_token"."

Ik geef deze wel mee hier:
https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/3d87748d8afc3827541a22711ed6e37ffe262c7a/pages/api/post.js#L11
Alvast bedankt!

**Comment by SimonVanherweghe** [comment]
Je hoeft helemaal geen fetch te doen als je de client library gebruikt (dat is het makkelijkste)

Dan kan je zo iets doen:
```javascript
import { createClient as deliveryClient } from "contentful";

export const getPosts = async (limit) => {
  const client = deliveryClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    environment: "master",
    accessToken: process.env.CONTENTFUL_ACCES_KEY,
  });

  return await client
    .getPosts({
      content_type: "post"
    })
    .catch(console.error);
};
```

Je kan dan in jouw eigen API route die getPosts functie importeren.
